/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Language } from "./global.types";
export namespace Components {
    interface WidgetXxilk {
        "amount": number;
        "hash": string;
        "language": Language;
    }
}
declare global {
    interface HTMLWidgetXxilkElement extends Components.WidgetXxilk, HTMLStencilElement {
    }
    var HTMLWidgetXxilkElement: {
        prototype: HTMLWidgetXxilkElement;
        new (): HTMLWidgetXxilkElement;
    };
    interface HTMLElementTagNameMap {
        "widget-xxilk": HTMLWidgetXxilkElement;
    }
}
declare namespace LocalJSX {
    interface WidgetXxilk {
        "amount"?: number;
        "hash"?: string;
        "language"?: Language;
    }
    interface IntrinsicElements {
        "widget-xxilk": WidgetXxilk;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "widget-xxilk": LocalJSX.WidgetXxilk & JSXBase.HTMLAttributes<HTMLWidgetXxilkElement>;
        }
    }
}
